### ISSUE TITLE
Could you please add some `toString` function in generated code?

### ISSUE THREAD

**Issue by linkdesu** [driftluo/moleculec-go#1]
Hi, Im a new to rust and dont know anything about go, but I need go generate some go code from schema for my partners. They want to print molecule data in development environment, but the lack of `toString` make it impossible.

So, I want to ask if you could help me this out? THX for what you have done.

**Comment by driftluo** [comment]
There is indeed no definition of the `ToString` method, but `AsSlice` returns all the data inside the molecule struct, user can convert `[]byte` into a hexadecimal String to print

`ToString` function is actually puzzling. Should it return a hexadecimal String or a pure binary list, or other expressions?

**Comment by linkdesu** [comment]
Thank you for providing a better solution. 👍
